import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import TooltipProvider from "@/provider/TooltipProvider";
import React from "react";
import Header from "@/components/testfoler/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout(props: {
  children: React.ReactNode;
  list: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TooltipProvider>
          <Header />
          {props.children}
        </TooltipProvider>
      </body>
    </html>
  );
}
