import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import TooltipProvider from "@/provider/TooltipProvider";
import React from "react";
import Header from "@/components/testfoler/header";
import ReactQueryProvider from "@/provider/ReactQueryProvider";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout(props: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReactQueryProvider>
          <TooltipProvider>
            <Header />
            {props.children}
          </TooltipProvider>
        </ReactQueryProvider>
        <Toaster
          position="top-center"
          gutter={8}
          toastOptions={{
            success: {
              duration: 3000,
            },
            error: {
              duration: 5000,
            },
          }}
        />
      </body>
    </html>
  );
}
